### ISSUE TITLE
Build fails in Linux (64-bit)

### ISSUE THREAD

**Issue by sumpygump** [ryanflannery/vitunes#34]
I get numerous errors (looks like a problem with ncurses?) when attempting to build on Ubuntu 12.10 (64-bit) with the linux branch of vitunes.

```
cc -o vitunes -lm -lncursesw -lutil `taglib-config --libs` -ltag_c commands.o compat.o e_commands.o keybindings.o medialib.o meta_info.o mplayer.o paint.o player.o player_utils.o playlist.o socket.o str2argv.o uinterface.o vitunes.o
commands.o: In function `cmd_color':
commands.c:(.text+0x1186): undefined reference to `init_pair'
commands.o: In function `cmd_set':
commands.c:(.text+0x12bf): undefined reference to `stdscr'
commands.c:(.text+0x12cb): undefined reference to `stdscr'
commands.o: In function `user_getstr':
commands.c:(.text+0x1e53): undefined reference to `werase'
commands.c:(.text+0x1e7d): undefined reference to `mvwprintw'
commands.c:(.text+0x1e87): undefined reference to `curs_set'
commands.c:(.text+0x1ea9): undefined reference to `wmove'
commands.c:(.text+0x1eb8): undefined reference to `wrefresh'
commands.c:(.text+0x1f1b): undefined reference to `curs_set'
commands.c:(.text+0x1f2f): undefined reference to `curs_set'
commands.c:(.text+0x1f58): undefined reference to `wmove'
commands.c:(.text+0x1f67): undefined reference to `wrefresh'
commands.c:(.text+0x1fe5): undefined reference to `beep'
commands.c:(.text+0x2016): undefined reference to `wmove'
commands.c:(.text+0x202f): undefined reference to `waddch'
commands.c:(.text+0x205b): undefined reference to `wmove'
....
```

Note that I get the same compilation errors with the master branch.

Here is a listing of curses packages I have installed (with a grep of curses):

```
$ dpkg -l | grep curses
ii  canto                                       0.7.10-4                                   amd64        flexible ncurses Atom/RSS newsreader for the console
ii  lib32ncurses5                               5.9-10ubuntu1                              amd64        shared libraries for terminal handling (32-bit)
rc  lib32ncursesw5                              5.9-4                                      amd64        shared libraries for terminal handling (wide character support) (32-bit)
ii  libncurses5:amd64                           5.9-10ubuntu1                              amd64        shared libraries for terminal handling
ii  libncurses5:i386                            5.9-10ubuntu1                              i386         shared libraries for terminal handling
ii  libncurses5-dev                             5.9-10ubuntu1                              amd64        developer's libraries for ncurses
ii  libncursesw5:amd64                          5.9-10ubuntu1                              amd64        shared libraries for terminal handling (wide character support)
ii  libncursesw5-dev                            5.9-10ubuntu1                              amd64        developer's libraries for ncursesw
ii  moc                                         1:2.5.0~alpha4+svn20120224-1ubuntu1        amd64        ncurses based console audio player
ii  mtr-tiny                                    0.82-3ubuntu1                              amd64        Full screen ncurses traceroute tool
ii  ncurses-base                                5.9-10ubuntu1                              all          basic terminal type definitions
ii  ncurses-bin                                 5.9-10ubuntu1                              amd64        terminal-related programs and man pages
ii  ncurses-term                                5.9-10ubuntu1                              all          additional terminal type definitions
ii  ninvaders                                   0.1.1-3                                    amd64        A space invaders-like game using ncurses
ii  python-urwid                                1.0.1-2                                    amd64        curses-based UI/widget library for Python
ii  ranger                                      1.5.4-1                                    all          File manager with an ncurses frontend written in Python
ii  rtorrent                                    0.9.2-1                                    amd64        ncurses BitTorrent client based on LibTorrent from rakshasa
ii  vifm                                        0.4-1ubuntu3                               amd64        a ncurses based file manager with vi like keybindings
ii  weechat-curses                              0.3.8-1                                    amd64        Fast, light and extensible chat client - console client
```

Is there a specific dependency I need to install that would clear this up? Any help would be appreciated.
